### ISSUE TITLE
progress bar

### ISSUE THREAD

**Issue by mjhea0** [brandon-rhodes/uncommitted#19]
thoughts on adding a progress bar or percentage completed?

**Comment by brandon-rhodes** [comment]
Well, that's an interesting idea — but: how would it know, as it went along, what % of the filesystem it had left?

**Comment by mjhea0** [comment]
You would have to:

1) do a scan to figure out the # of repos
2) then do the check

I know that's more work but mine ran for an hour and I just wanted to know what was happening. 

You could also have it do an optional commit. Right now I am cleaning up my file system and moving computers so I could just have a basic comment in the git commit like - "closing down computer, ignore this poor commit message"

**Comment by brandon-rhodes** [comment]
Wow, more than an hour! I wonder if we can figure out why it is taking so long? My guess is that, given the two steps that you suggested, that nearly all of the time would be spent in step 1, so that the user experience would be that Uncommitted runs for 70 minutes looking for the # of repos, and then is able to display a progress bar for the final 3 minutes it spends running `git status` (or whatever) on the repositories that it finds.

**Comment by mjhea0** [comment]
Good point. How about just a status bad that shows the current directory being scanned?

**Comment by brandon-rhodes** [comment]
I don't have any objection to an option like `--progress` or something that would turn on some kind of printing to stderr that keeps the user up to date on where the scan is, though obviously for most users that will just slow things down.

Did you ever figure out what was making uncommitted take an hour to scan your machine? I would prefer to get that fixed if we could!

**Comment by brandon-rhodes** [comment]
I'm going to temporarily close this, pending further information about why uncommitted takes >1 hour on some machines. Simply comment again in the future if more information turns up. Thanks!
